[project]
name = "attention-viewer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.2",
    "torch>=2.8.0",
    "transformer-lens>=2.15.4",
    "transformers>=4.55.0",
]
